apiVersion: v1
kind: Service
metadata:
  name: pryzintul-calc-engine-service
  namespace: default
  labels:
    name: pryzintul-calc-engine
spec:
  type: LoadBalancer
  selector:
    name: pryzintul-calc-engine
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP